### ISSUE TITLE
Why the evaluation is slow?

### ISSUE THREAD

**Issue by EudicL** [TooTouch/MemSeg#9]
The process takes up half of my training time.

**Comment by tootouch** [comment]
Hi, @EudicL 

AUPRO has the biggest impact on the reason why the evaluation takes a long time.

AUPRO, like AUROC, is a threshold independent metric. AUPRO binarizes the predicted pixel-level anomaly score for each threshold for one image, and calculates the IOU with ground truth mask. Therefore, the evaluation is time consuming because it requires the same process for all the test images.
